services:
  postgres:
    image: postgres:18.0
    container_name: slb_postgres
    environment:
      POSTGRES_USER: harshit
      POSTGRES_PASSWORD: Harshit@7505
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    #volumes:
    #  - ./pgdata:/var/lib/postgresql/data
    #command: ["postgres", "-c", "max_connections=500", "-c", "shared_buffers=1GB"]

  redis_cache:
    image: redis:8.2.1
    container_name: redis_cache
    ports:
      - "6380:6379"

  redis_queue:
    image: redis:8.2.1
    container_name: redis_queue
    ports:
      - "6381:6379"

  backend:
    build: .
    container_name: slb_backend
    depends_on:
      - postgres
      - redis_cache
      - redis_queue
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: ["npx", "pm2-runtime", "ecosystem.config.js", "--env", "production"]
  
